[workspace]
members = [
  "nft",
  "test-approval-receiver",
  "test-token-receiver",
]
exclude = [
  "integration-tests"
]

[patch.crates-io]
parity-secp256k1 = { git = "https://github.com/paritytech/rust-secp256k1.git" }