[package]
name = "test-approval-receiver"
version = "0.1.0"
edition = "2018"

[dependencies]
near-sdk = "4.1.1"
near-contract-standards = "4.0.0"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true